# Generated by Django 5.2.17 on 2026-08-23 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True, max_length=1000, null=True)),
                ("posted_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacancies",
                        to="vacancies.company",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="vacancies", to="vacancies.source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VacancyState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("saved", models.BooleanField(default=False)),
                ("hidden", models.BooleanField(default=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("vacancy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vacancies.vacancy")),
            ],
        ),
        migrations.AddConstraint(
            model_name="vacancy",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"), name="vacancies_vacancy_source_external_id_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancystate",
            constraint=models.UniqueConstraint(fields=("user", "vacancy"), name="vacancies_state_user_vacancy_uniq"),
        ),
    ]
