# Generated by Django 5.2.17 on 2026-08-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="location",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
