# Generated by Django 5.2.17 on 2026-08-24 00:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0004_populate_source_icons"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_deftech",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="is_deftech",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="scraped_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
