# Generated by Django 5.2.17 on 2026-08-24 01:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0005_company_is_deftech_vacancy_is_deftech_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VacancyMatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("precise", models.BooleanField(default=False)),
                ("scored_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancy_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="matches", to="vacancies.vacancy"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("user", "vacancy"), name="vacancies_match_user_vacancy_uniq"),
                    models.CheckConstraint(
                        condition=models.Q(("score__lte", 100)), name="vacancies_match_score_lte_100"
                    ),
                ],
            },
        ),
    ]
