# Generated by Django 5.2.17 on 2026-08-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0006_vacancymatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancystate",
            name="seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
