# Generated by Django 5.2.17 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0008_vacancyapplication_vacancynote"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="description_format",
            field=models.CharField(
                choices=[("source", "Source text"), ("markdown", "Markdown")],
                default="source",
                max_length=8,
            ),
        ),
    ]
