# Generated by Django 5.2.17 on 2026-10-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0009_vacancy_description_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="description_format",
            field=models.CharField(
                choices=[("source", "Source text"), ("markdown", "Markdown")],
                db_default="source",
                default="source",
                max_length=8,
            ),
        ),
    ]
