# Generated by Django 5.2.17 on 2026-09-24 20:04

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vacancies", "0008_vacancyapplication_vacancynote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=30),
                ),
                (
                    "stop_words",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), blank=True, default=list, size=30
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sources", models.ManyToManyField(blank=True, related_name="interests", to="vacancies.source")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("keywords__len__gt", 0)), name="interests_interest_keywords_not_empty"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("keywords__len__lte", 30)), name="interests_interest_keywords_max"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("stop_words__len__lte", 30)), name="interests_interest_stop_words_max"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True), name="interests_interest_name_not_empty"
                    ),
                ],
            },
        ),
    ]
